### ISSUE TITLE
New Column Breaks Code

### ISSUE THREAD

**Issue by mphillips12** [laralee3/restaurantAdder#8]
ISSUE:

After adding 'Country' column to the Google Sheets, imported restaurants have data shifted to the wrong columns

STEPS TO REPRO:

1. Go to Google Sheet > Insert a blank column to the right of Zip Code column
2. Add the "Country Column" from sandbox sheet to the position after Zip Code
3. Navigate to Restaurant Adder
4. Add any new restaurant
5. View the Google Sheet

ACTUAL:

Information is imported to the incorrect fields

EXPECTED:

Information still imports to the correct column

ADDITIONAL INFO:

![shifted](https://cloud.githubusercontent.com/assets/28489499/26319559/5b419766-3ed4-11e7-8fab-1c12f14c06b1.png)

**Comment by mphillips12** [comment]
@laralee3 is there a way for the Restaurant Adder code to read the column header names so that info still goes to the correct column in the event we add/remove columns from the main Google sheet?

**Comment by laralee3** [comment]
There is but it's a bit more of a timesink, which is why I didn't do it initially. Same with international addresses

**Comment by mphillips12** [comment]
Sonnaaaa....

**Comment by laralee3** [comment]
@mphillips12 This is fixed. I will have to update to add new data to new columns, but changing column order won't matter anymore.

**Comment by mphillips12** [comment]
@laralee3 Ok. For now I removed the "row id" column because the restaurants aren't added automatically in alphabetical order. I can add it back if/when we include logic to add a restaurant to the list in ABC order
